/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.retrylife.minecraft.mods.vping;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
